export const sessionCatalog = [
  {
    id: 'sess-101',
    child: 'Omar Ahmed',
    sessionType: 'Behavior Therapy',
    doctorName: 'Dr. Ahmed Ali',
    therapistName: 'Ther. Amany Ebrahim',
    specialization: 'Behavior Therapist',
    dateLabel: 'Apr 11, 2026',
    timeLabel: '09:00 AM',
    status: 'Confirmed',
    mode: 'Zoom',
    meetingLabel: 'Join Zoom',
    meetingLink: 'https://zoom.us/j/123456',
    notesLabel: 'Parent prep',
    notesSummary: 'Bring favorite visual cards and review last home routine note before the session.',
    lastSummary: 'Omar kept eye contact for longer during imitation play and followed two-step prompts with support.',
    assignedTo: ['parent', 'doctor', 'therapist'],
    homeRoleLabel: {
      parent: 'Next session',
      doctor: 'Patient session',
      therapist: 'Assigned session',
    },
  },
  {
    id: 'sess-102',
    child: 'Lina Samir',
    sessionType: 'Doctor Review',
    doctorName: 'Dr. Ahmed Ali',
    therapistName: 'Ther. Rania Fikrat',
    specialization: 'Speech Therapist',
    dateLabel: 'Apr 12, 2026',
    timeLabel: '11:00 AM',
    status: 'Upcoming',
    mode: 'Google Meet',
    meetingLabel: 'Join Google Meet',
    meetingLink: 'https://meet.google.com/abc-def',
    notesLabel: 'Clinical note',
    notesSummary: 'Review progress report trends before confirming the next treatment plan adjustment.',
    lastSummary: 'Lina initiated five target words independently and tolerated short phrase modeling.',
    assignedTo: ['parent', 'doctor'],
    homeRoleLabel: {
      parent: 'Upcoming review',
      doctor: 'Patient session',
      therapist: 'Assigned session',
    },
  },
  {
    id: 'sess-103',
    child: 'Youssef Khaled',
    sessionType: 'Occupational Therapy',
    doctorName: 'Dr. Salma Hassan',
    therapistName: 'Ther. Maha Salem',
    specialization: 'Occupational Therapist',
    dateLabel: 'Apr 13, 2026',
    timeLabel: '01:30 PM',
    status: 'Needs confirmation',
    mode: 'Zoom',
    meetingLabel: 'Join Zoom',
    meetingLink: 'https://zoom.us/j/123456',
    notesLabel: 'Therapy plan',
    notesSummary: 'Confirm sensory regulation materials and share a short pre-session update with the family.',
    lastSummary: 'Youssef completed sensory transitions more calmly when offered a predictable sequence board.',
    assignedTo: ['doctor', 'therapist'],
    homeRoleLabel: {
      parent: 'Next session',
      doctor: 'Patient session',
      therapist: 'Assigned session',
    },
  },
]

export const messageThreads = [
  {
    id: 'doctor-thread',
    userId: 'doctor-thread',
    participantName: 'Dr. Ahmed Ali',
    participantRole: 'Doctor',
    participantSubtitle: 'Child Neurologist',
    avatar: 'DA',
    lastMessage: 'I reviewed the screening result and added a note to the report.',
    time: '09:24',
    unread: 1,
    typing: false,
    participants: ['parent', 'doctor'],
    messages: [
      { id: 'm-1', sender: 'doctor', text: 'Good morning. I reviewed Omar’s screening result this morning.', time: '09:10' },
      { id: 'm-2', sender: 'parent', text: 'Thank you. Can we align on the next doctor review?', time: '09:16' },
      { id: 'm-3', sender: 'doctor', text: 'I reviewed the screening result and added a note to the report.', time: '09:24' },
    ],
  },
  {
    id: 'therapist-thread',
    userId: 'therapist-thread',
    participantName: 'Ther. Amany Ebrahim',
    participantRole: 'Therapist',
    participantSubtitle: 'Behavior Therapist',
    avatar: 'AE',
    lastMessage: 'Let’s keep the visual routine short and repeat it after lunch.',
    time: 'Yesterday',
    unread: 0,
    typing: true,
    participants: ['parent', 'therapist', 'doctor'],
    messages: [
      { id: 'm-4', sender: 'therapist', text: 'Omar responded well to the matching game today.', time: '16:02' },
      { id: 'm-5', sender: 'parent', text: 'Great. Which home task should we repeat tonight?', time: '16:07' },
      { id: 'm-6', sender: 'therapist', text: 'Let’s keep the visual routine short and repeat it after lunch.', time: '16:11' },
    ],
  },
  {
    id: 'parent-thread',
    userId: 'parent-thread',
    participantName: 'John Parent',
    participantRole: 'Parent',
    participantSubtitle: 'Family contact',
    avatar: 'JP',
    lastMessage: 'Please send me the final session summary when it is ready.',
    time: '08:40',
    unread: 2,
    typing: false,
    participants: ['doctor', 'therapist', 'parent'],
    messages: [
      { id: 'm-7', sender: 'parent', text: 'Please send me the final session summary when it is ready.', time: '08:40' },
    ],
  },
]

export const specialistDirectory = [
  {
    id: 'sp-1',
    name: 'Dr. Ahmed Ali',
    type: 'Doctor',
    specialization: 'Child Neurology',
    experience: '10 years',
    availability: 'Available this week',
    avatar: 'DA',
    focus: 'Development reviews, medication plans, multidisciplinary coordination',
  },
  {
    id: 'sp-2',
    name: 'Ther. Amany Ebrahim',
    type: 'Therapist',
    specialization: 'Behavior Therapy',
    experience: '7 years',
    availability: 'Next slot tomorrow',
    avatar: 'AE',
    focus: 'Routine-building, imitation, engagement, parent coaching',
  },
  {
    id: 'sp-3',
    name: 'Ther. Rania Fikrat',
    type: 'Therapist',
    specialization: 'Speech Therapy',
    experience: '6 years',
    availability: 'Open on Monday',
    avatar: 'RF',
    focus: 'Expressive language, articulation, turn-taking communication',
  },
  {
    id: 'sp-4',
    name: 'Dr. Salma Hassan',
    type: 'Doctor',
    specialization: 'Developmental Pediatrics',
    experience: '12 years',
    availability: 'Review slots on Tuesday',
    avatar: 'SH',
    focus: 'Progress tracking, family guidance, integrated treatment planning',
  },
]

export const reportsOverview = {
  summary: [
    { id: 'sum-1', label: 'Child progress', value: '78%', tone: 'sky' },
    { id: 'sum-2', label: 'Screening result', value: 'Moderate', tone: 'amber' },
    { id: 'sum-3', label: 'Sessions completed', value: '24', tone: 'emerald' },
    { id: 'sum-4', label: 'Behavior stability', value: '+12%', tone: 'violet' },
  ],
  cards: [
    {
      id: 'rep-1',
      title: 'Child progress report',
      description: 'Milestones across communication, attention, and routine follow-through.',
      metric: 'Communication accuracy 82%',
      accent: 'sky',
    },
    {
      id: 'rep-2',
      title: 'Screening result',
      description: 'Latest screening score and risk guidance from the current review cycle.',
      metric: 'Score 14/20, moderate follow-up needed',
      accent: 'amber',
    },
    {
      id: 'rep-3',
      title: 'Sessions summary',
      description: 'Attendance, completed care touchpoints, and session-note coverage.',
      metric: '6 sessions this month, 100% note submission',
      accent: 'emerald',
    },
    {
      id: 'rep-4',
      title: 'Therapy progress',
      description: 'Goal completion across therapy plans and parent home carry-over.',
      metric: '3 of 4 weekly goals on track',
      accent: 'violet',
    },
  ],
  progressTrend: [
    { name: 'Week 1', communication: 48, engagement: 56, behavior: 52 },
    { name: 'Week 2', communication: 59, engagement: 61, behavior: 57 },
    { name: 'Week 3', communication: 68, engagement: 70, behavior: 65 },
    { name: 'Week 4', communication: 78, engagement: 74, behavior: 71 },
  ],
  behaviorStats: [
    { name: 'Calm transitions', value: 32 },
    { name: 'Prompted routines', value: 24 },
    { name: 'Independent responses', value: 19 },
    { name: 'Escalations', value: 7 },
  ],
  sessionMix: [
    { name: 'Therapy', value: 14 },
    { name: 'Doctor review', value: 6 },
    { name: 'Parent coaching', value: 4 },
  ],
}

export const roleSidebarSummary = {
  doctor: {
    eyebrow: 'Clinical workspace',
    title: 'Doctor dashboard',
    subtitle: 'Reviews, reports, and family coordination',
  },
  therapist: {
    eyebrow: 'Care delivery',
    title: 'Therapist dashboard',
    subtitle: 'Sessions, notes, and treatment follow-through',
  },
  parent: {
    eyebrow: 'Family space',
    title: 'Parent dashboard',
    subtitle: 'Sessions, reports, and messaging in one place',
  },
}
