export const sessionCatalog = [
  {
    id: 'sess-101',
    child: 'Omar Ahmed',
    sessionType: 'Behavioral Therapy Session',
    doctorName: 'Dr. Ahmed Mustafa',
    therapistName: 'Amani Ibrahim',
    specialization: 'Behavioral Therapy Specialist',
    dateLabel: 'April 11, 2026',
    timeLabel: '09:00 AM',
    status: 'Confirmed',
    mode: 'Zoom',
    meetingLabel: 'Join Zoom',
    meetingLink: 'https://zoom.us/j/123456',
    notesLabel: 'Pre-session Note',
    notesSummary: 'Review favorite picture cards with the child before the session and prepare a quick note on the morning routine.',
    lastSummary: 'Omar responded better to visual imitation and maintained eye contact for longer periods.',
    assignedTo: ['parent', 'doctor', 'therapist'],
    homeRoleLabel: {
      parent: 'Upcoming Session',
      doctor: 'Next Patient Session',
      therapist: 'Assigned Session',
    },
  },
  {
    id: 'sess-102',
    child: 'Yousef Mohammed',
    sessionType: 'Medical Review',
    doctorName: 'Dr. Mahmoud Khaled',
    therapistName: 'Sarah Ahmed',
    specialization: 'Speech & Language Therapist',
    dateLabel: 'April 12, 2026',
    timeLabel: '11:00 AM',
    status: 'Upcoming',
    mode: 'Google Meet',
    meetingLabel: 'Join Google Meet',
    meetingLink: 'https://meet.google.com/abc-def',
    notesLabel: 'Medical Note',
    notesSummary: 'Review progress summary before approving modifications to the treatment plan.',
    lastSummary: 'Yousef showed clear improvement in verbal response and independent use of target words.',
    assignedTo: ['parent', 'doctor'],
    homeRoleLabel: {
      parent: 'Upcoming Review',
      doctor: 'Next Patient Session',
      therapist: 'Assigned Session',
    },
  },
  {
    id: 'sess-103',
    child: 'Omar Hassan',
    sessionType: 'Occupational Therapy Session',
    doctorName: 'Dr. Ahmed Mustafa',
    therapistName: 'Sarah Ahmed',
    specialization: 'Occupational Therapy Specialist',
    dateLabel: 'April 13, 2026',
    timeLabel: '01:30 PM',
    status: 'Pending Confirmation',
    mode: 'Zoom',
    meetingLabel: 'Join Zoom',
    meetingLink: 'https://zoom.us/j/123456',
    notesLabel: 'Session Plan',
    notesSummary: 'Confirm required sensory tools and send a brief update to the family before the appointment.',
    lastSummary: "Omar Hassan's ability to transition between activities improved when using a consistent visual schedule.",
    assignedTo: ['doctor', 'therapist'],
    homeRoleLabel: {
      parent: 'Upcoming Session',
      doctor: 'Next Patient Session',
      therapist: 'Assigned Session',
    },
  },
]

export const messageThreads = [
  {
    id: 'doctor-thread',
    userId: 'doctor-thread',
    participantName: 'Dr. Ahmed Mustafa',
    participantRole: 'Doctor',
    participantSubtitle: 'Developmental & Behavioral Consultant',
    avatar: 'AM',
    lastMessage: 'I reviewed the screening result and added a note inside the report.',
    time: '09:24',
    unread: 1,
    typing: false,
    participants: ['parent', 'doctor'],
    messages: [
      { id: 'm-1', sender: 'doctor', text: "Good morning, I reviewed Omar Ahmed's screening result this morning.", time: '09:10' },
      { id: 'm-2', sender: 'parent', text: 'Thank you, can we coordinate the next review appointment?', time: '09:16' },
      { id: 'm-3', sender: 'doctor', text: 'I reviewed the screening result and added a note inside the report.', time: '09:24' },
    ],
  },
  {
    id: 'therapist-thread',
    userId: 'therapist-thread',
    participantName: 'Amani Ibrahim',
    participantRole: 'Therapist',
    participantSubtitle: 'Behavioral Therapy Specialist',
    avatar: 'AI',
    lastMessage: "Let's repeat the short visual routine after lunch today.",
    time: 'Yesterday',
    unread: 0,
    typing: true,
    participants: ['parent', 'therapist', 'doctor'],
    messages: [
      { id: 'm-4', sender: 'therapist', text: 'Omar Ahmed responded very well in the matching game today.', time: '16:02' },
      { id: 'm-5', sender: 'parent', text: 'Excellent, what home activity should we repeat this evening?', time: '16:07' },
      { id: 'm-6', sender: 'therapist', text: "Let's repeat the short visual routine after lunch today.", time: '16:11' },
    ],
  },
  {
    id: 'parent-thread',
    userId: 'parent-thread',
    participantName: 'Mohammed Ahmed',
    participantRole: 'Parent',
    participantSubtitle: 'Guardian',
    avatar: 'MA',
    lastMessage: 'Please send me the final summary after the session ends.',
    time: '08:40',
    unread: 2,
    typing: false,
    participants: ['doctor', 'therapist', 'parent'],
    messages: [
      { id: 'm-7', sender: 'parent', text: 'Please send me the final summary after the session ends.', time: '08:40' },
    ],
  },
]

export const specialistDirectory = [
  {
    id: 'sp-1',
    name: 'Dr. Ahmed Mustafa',
    type: 'Doctor',
    specialization: 'Developmental & Behavioral Pediatrics',
    experience: '10 years',
    availability: 'Available this week',
    avatar: 'AM',
    focus: 'Developmental follow-up, treatment planning, and family-team coordination.',
  },
  {
    id: 'sp-2',
    name: 'Dr. Mahmoud Khaled',
    type: 'Doctor',
    specialization: 'Pediatric Neurology',
    experience: '12 years',
    availability: 'Appointments available Tuesday',
    avatar: 'MK',
    focus: 'Medical reviews, progress evaluation, and treatment plan decision support.',
  },
  {
    id: 'sp-3',
    name: 'Sarah Ahmed',
    type: 'Therapist',
    specialization: 'Speech & Language Therapy',
    experience: '6 years',
    availability: 'Next available tomorrow',
    avatar: 'SA',
    focus: 'Improving expressive language, joint attention, and functional communication.',
  },
  {
    id: 'sp-4',
    name: 'Amani Ibrahim',
    type: 'Therapist',
    specialization: 'Behavioral Therapy',
    experience: '7 years',
    availability: 'Available Monday',
    avatar: 'AI',
    focus: 'Routine building, behavioral training, and family home guidance.',
  },
]

export const reportsOverview = {
  summary: [
    { id: 'sum-1', label: "Child's Progress", value: '78%', tone: 'sky' },
    { id: 'sum-2', label: 'Screening Result', value: 'Moderate', tone: 'amber' },
    { id: 'sum-3', label: 'Sessions Completed', value: '24', tone: 'emerald' },
    { id: 'sum-4', label: 'Behavior Stability', value: '+12%', tone: 'violet' },
  ],
  cards: [
    {
      id: 'rep-1',
      title: "Child's Progress Report",
      description: 'Summary of communication, attention, and routine adherence during the last care cycle.',
      metric: 'Communication accuracy 82%',
      accent: 'sky',
    },
    {
      id: 'rep-2',
      title: 'Screening Result',
      description: 'Latest screening result with a clear recommendation for the next follow-up.',
      metric: 'Score 14/20 — needs follow-up',
      accent: 'amber',
    },
    {
      id: 'rep-3',
      title: 'Session Summary',
      description: 'Session attendance, note completion, and weekly plan progress.',
      metric: '6 sessions this month',
      accent: 'emerald',
    },
    {
      id: 'rep-4',
      title: 'Treatment Progress',
      description: 'Tracking therapy goals and family engagement with home tasks.',
      metric: '3 of 4 goals on track',
      accent: 'violet',
    },
  ],
  progressTrend: [
    { name: 'Week 1', communication: 48, engagement: 56, behavior: 52 },
    { name: 'Week 2', communication: 59, engagement: 61, behavior: 57 },
    { name: 'Week 3', communication: 68, engagement: 70, behavior: 65 },
    { name: 'Week 4', communication: 78, engagement: 74, behavior: 71 },
  ],
  behaviorStats: [
    { name: 'Calm Transitions', value: 32 },
    { name: 'Assisted Routines', value: 24 },
    { name: 'Independent Responses', value: 19 },
    { name: 'Distress Episodes', value: 7 },
  ],
  sessionMix: [
    { name: 'Therapy Sessions', value: 14 },
    { name: 'Medical Reviews', value: 6 },
    { name: 'Family Guidance', value: 4 },
  ],
}

export const sessionNotesArabic = [
  {
    id: 'note-1',
    child: 'Omar Ahmed',
    date: 'April 10, 2026',
    sessionType: 'Behavioral Therapy Session',
    summary: 'Improvement in response to visual stimuli and ability to wait their turn for longer periods.',
    nextStep: 'Repeat the visual imitation game twice daily at home.',
  },
  {
    id: 'note-2',
    child: 'Yousef Mohammed',
    date: 'April 9, 2026',
    sessionType: 'Speech Session',
    summary: 'Produced five target words independently with clear improvement in attention.',
    nextStep: 'Progress to short two-word sentences with visual support.',
  },
]

export const homeNotesArabic = [
  {
    id: 'home-1',
    date: 'April 10, 2026',
    title: 'Morning Home Note',
    note: 'Omar Ahmed responded well to the morning routine and was calmer before the session.',
  },
  {
    id: 'home-2',
    date: 'April 9, 2026',
    title: 'After Lunch Note',
    note: 'Yousef Mohammed repeated the matching activity twice and requested the pictures himself.',
  },
]

export const retestOverview = {
  schedule: [
    { label: 'Last Test', value: 'April 2, 2026' },
    { label: 'Next Test', value: 'April 16, 2026' },
    { label: 'Recommended Frequency', value: 'Every 2 weeks or after behavior changes' },
  ],
  summaryTitle: 'Last Test Summary',
  summaryRisk: 'Moderate Risk',
  summaryScore: '14 out of 20 indicators',
  guidance: [
    'Re-test after any noticeable change in routine or therapeutic response.',
    'Use the screening result to update the home overview and reports before the next visit.',
  ],
}

export const roleSidebarSummary = {
  doctor: {
    eyebrow: 'Clinical workspace',
    title: 'Doctor Dashboard',
    subtitle: 'Reviews, reports, and family coordination',
  },
  therapist: {
    eyebrow: 'Care delivery',
    title: 'Therapist Dashboard',
    subtitle: 'Sessions, notes, and treatment follow-through',
  },
  parent: {
    eyebrow: 'Family space',
    title: 'Parent Dashboard',
    subtitle: 'Sessions, reports, and messaging in one place',
  },
}
